nobleTilePoints=3
pointsToWin=15

startingGems2Players=4
startingGems3Players=5
startingGems4Players=7

deck1=src/data/deck1.csv
deck2=src/data/deck2.csv
deck3=src/data/deck3.csv
nobletiles=src/data/nobletiles.csv